### ISSUE TITLE
TextParameter is not functional

### ISSUE THREAD

**Issue by Squashhh** [Synopsie/Iriss-Command#1]
In fact, only one word is accepted in the argument against several normally...
It has the same effect as a StringParameter

` class TestCommand extends CommandBase {

    public function __construct()
    {
        parent::__construct("test", "commande de test", "/test [reason]", [], []);
        $this->setPermissions([DefaultPermissions::ROOT_USER]);
    }

    public function getCommandParameters(): array
    {
        return [
            new TextParameter("reason", false)
        ];
    }

    protected function onRun(CommandSender $sender, array $parameters): void
    {
        $sender->sendMessage($parameters["reason"]);
    }
} `

![image](https://github.com/user-attachments/assets/619e207f-e521-4463-b913-2c5d6fee6b5b)

**Comment by Dumont-Julien** [comment]
Fix in v1.1.2
